### ISSUE TITLE
AcquirerGuard -IIN [8pt]

### ISSUE THREAD

**Issue by nilssonemma** [payfunc/selectively#99]
## Tasks

- [ ] Create interface (Guard) (in new repo). Test bin implementation [2pt]
- [ ] Implement in-functions for arrays in selectively [2pt]
- [ ] Create state storage durable object (new repo) [3pt]
- [ ] Create bin key value store [1pt]

## Notes
- Interface: read write functions
- email, card, ip (plus merchant id)
- https://binlist.net/ Save everything and date

bin: {...binlist, expires}
